USB_VID = 0x0900
USB_PID = 0x0901
USB_PRODUCT = "ESP32-S3-DUET-YADA-1"
USB_MANUFACTURER = "V.I. Integration"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB
